### ISSUE TITLE
Horizontal drawing on chrome

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#105]
On Chrome it seems a bit random how some indicators are drawn when the groups are added. Firefox seems to do this better. Any way we can solve these situations better on Chrome? See example:
![Chrome drawing badly.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46cb9c882c8f86e98bfbbe54ad53f7d42b47237f3046ef696097ec22ba416f43554d4ba4125d5715aafe807af7b03c218a5c09bed3690e70c23c03b0aac04ee155e57dd205d0f4ae805ec1e03724e28a8a4b3c19071b89fb5e37b2d4.PNG)

**Comment by adrianq** [comment]
We don't fully understand what the problem is...  Is that the text fields are displayed in a column? This is because there isn't enough space because of the long data element title. We can explore another solution like truncating the data element title by restricting the width to 50% or allows multi-line. Do you want us to go for that? What is in your opinion the best solution?

**Comment by troyel** [comment]
It would be great if we can find a way to better utilize the white open space. And yes try to move the section header to its own row or multi-line the indicator name whatever the problem is. We would like to avoid both horizontal and unnecessary vertical scrolling - as far as we can :-)

**Comment by adrianq** [comment]
Got it! We will have a look at it!

**Comment by adrianq** [comment]
Updating this card so we have all the information to discuss it on Wed:
The problem here is that with no split, even if the data element column takes only 71px, there is no room for all the data values. So it decides to split (that's what the screenshot shows), and just a one-level split results in one table per IDP-Male/Famale, one for Regufee-Male/Female, etc.

The only option we had is to split columns evenly, regardless of the catcombos, in 2 parts/3/4/... until it fits. The code will be a more complex, but we won't have the limitations we are seeing. However, imho it would be a bit difficult to understand for the users...
