### ISSUE TITLE
configuration standard value on the DE status group

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#110]
Hia,
For some reason each time I start the app on a fresh db copy it doesn't have pre-selected the data element status group (but it has all the others). Dunno what causes this but if it is a quick fix that would be great to do so it doesn't have to get updated each day.
![data element status group standard value empty.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46ec958e22c286a58ae4ba4db01de380285232606903b1246595a33bab4375050e1d1abc07090301a9e9dc76e6f27562964e4baf8e370a27822f1bbebd8a4cba09eb768c46d4e7ba8a1dc0e83f76e58fde4b3a1f17049bbd0c6bf4c6169112a309f34747a5143c62e377307e40941f71246e6322b9b1.PNG)

**Comment by tokland** [comment]
Testing with the new database (backups_latestgors.nrc.no_db_dhis2_2.26-5721b33_20180118T033703Z.sql.gz), I see the element correctly:

![screenshot from 2018-01-18 12-49-16](https://user-images.githubusercontent.com/24643/35096890-25ab1a22-fc4e-11e7-9176-1656606f879d.png)

The default value for this field is `code:eq:GL_DESTATUS_DEGROUPSET`, which exists:

![screenshot from 2018-01-18 12-49-28](https://user-images.githubusercontent.com/24643/35096907-359b6c7a-fc4e-11e7-8b0f-7b89cbe76d3e.png)

I am a bit confused because I am pretty sure this group set already existed previously. Troyel, do you see it selected now? if not, which user are you using to enter the settings?

**Comment by tokland** [comment]
Sorry, the screenshot I posted actually shows the problem: `GL_DESTATUS_DEGROUPSET` is set as description, it should be its code. Fixed in dev.est, should be fixed also the original DB.
