### ISSUE TITLE
Fix feedback tool

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#124]

**Comment by ardhimanshu** [comment]
A bit unintuitive (perhaps message should be more clear when we select "send feedback". As I see, by default it selects the whole screen. Then one chooses which portion to highlight and which to black out. Since it allows for rectangular selection, what if one needs to black out a portion from the highlighted portion? Probably the wording can be more logical here explaining the exact logical process.

In addition, while trying the function, got an error (attached).
![DC_App_Feedback_Tool_Error_Screenshot.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a82a9ba56ec00001202c168/125516c66e82c728ace21e0d46ccb7a502929396a9ecba47a65cf39f1672287c253b8639628af1178c4169040a010df41e1c4d58eeb9cb74fce36f34985619e8d93e5a7c976b16a5e9d319bf50ba20891c87b2ed8e48c1fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e04d51a61a3266ef72316e0a.PNG)

**Comment by adrianq** [comment]
What version of the app are you using? You should be using the last one: https://github.com/EyeSeeTea/dataset-configuration-blessed/releases/tag/v0.8.2 that actually fixes this problem. You can double check this by going into the 'App Management' app in dhis2.

Re your other comments, probably the best way is to just black out whatever you want and then explain what you want to highlight in the description. I understand your point but we are using an open source library that we have modified to provide a better user experience. It is gonna take some time to make the changes you are suggesting and I am unsure what real impact this is actually gonna have on the users. If you think this is actually a big deal just let me know and we will explore a bit more if we can make more changes to the library and how long it will take.

No problem with changing the wording. What do you have in mind?

**Comment by ardhimanshu** [comment]
Ok. Lets keep the wording as it is for now. By the way, "who" receives the feedback? Are there any email ids set or does it send feedback in the messages on GORS system? How to access the feedback?

**Comment by ardhimanshu** [comment]
Just noted in the manual that it goes to EyeSeeTea. However, I am wondering if there is anyway the feedback could come to us. This is because we have several field offices and if they encounter any problem while creating a dataset. they could use this feedback functionality to send their question to us - which we can try to resolve. If the question really pertains to something relevant for EyeSeeTea, we can forward you the same. What do you think?

**Comment by adrianq** [comment]
It just creates an issue in the waffle board. You can see the one you have just created here: https://waffle.io/EyeSeeTea/dataset-configuration-blessed/cards/5aabb7f58eabdf01163921d6 If you prefer we can also change it to send an internal message to a certain user group in Dhis2 too or just one of the two... as you wish...

**Comment by ardhimanshu** [comment]
I think it is best that it comes to GL_SysAdmin in GORS. We review it and if it related to any development aspects of app, we raise issue on waffle.

**Comment by adrianq** [comment]
Sounds good to me. Just in case, when a new data set is created/edited we currently send an internal notification to GL_M&E user group. Do you prefer to use GL_SysAdmin instead for this feedback thing? Any option is fine with us but just wanted to make the point so you are aware of the different groups/purposes...

**Comment by adrianq** [comment]
Feedback tool is fixed so I am closing this one... I have created #130 to modify the feedback tool and send an internal message instead of  opening a waffle card.
