### ISSUE TITLE
Confusion over editing DataSet

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#132]
DataSet created after linking to a project. When one wants to edit and during that process. As a first step, if I got to project selection and decide not to choose any specific project (thinking that the old project it was linked to will continue to hold) and proceed with the next steps. At the last step, I do not see "project" in the final summary.
Image attached in comment for reference.

**Comment by ardhimanshu** [comment]
Image for reference.
![Issue_132_in_Waffle_for_DC_App.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a82a9ba56ec00001202c168/125516c66e82c728ace21e0d46c187893687bcf8dcbb804aaa62c7952f402b761602ac394fa1c0179e526b43434d0eee1e020a17b8eb8339a3be6f75820d5dead83c0e72c66c11acbad11dbb50be248a5d99a4fedb1294b7607caddecd5d340c071883fe5837a19f4eca5bf74fe14857b65e.png)

**Comment by tokland** [comment]
Your expectation is correct, when editing a dataset, the associated project is kept. 

The problem is: for this to work, the full name of the dataset must be part of the name of the project. That's not arbitrary, DHIS2 datasets cannot directly reference a project (categoryOption). Therefore, we must rely on naming conventions. Let's see the details:

Project name: `IRFM1801 (NMFA (HUM))`
Current dataset name: `IRFM1801_dataset_(NMFA (HUM))`

This `_dataset_` in the middle of the name breaks the convention. Correct dataset name should fully include the project name, for example: `IRFM1801 (NMFA (HUM)) Dataset`. Once you rename it (either using the app or `Maintenance`), the association should be shown on the next edit. Can you confirm?

**Comment by ardhimanshu** [comment]
So you mean it should work when the term "DataSet" is put at the end of the DataSet name: For example, IRFM1801 (NMFA (HUM))_DataSet.

**Comment by tokland** [comment]
> For example, IRFM1801 (NMFA (HUM))_DataSet.

Yes, that should work, as it fully includes `IRFM1801 (NMFA (HUM))`.
