### ISSUE TITLE
CustomJS /CSS

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#133]
I understand that this particular feature had been mentioned in one of our earlier calls. I am not quite sure how this works (in connection with DataSet Configuration App), what process we need to follow to use this and what results do we expect based on this. From our earlier discussion it seemed like we need to include it while using the app. Can we have a brief call to discuss the same?

**Comment by adrianq** [comment]
@ardhimanshu  I have updated the documentation to provide you with a better explanation regarding this feature. You can find it [here](https://docs.google.com/document/d/1BED4QKxkAYbvgl3tFvG8Yr0xpC9cZ1xtAnjtR7QAcPw/edit#heading=h.bub5av85w40s). 

Find below as well the content of the section (links are not working here so you will have to go to the Google Doc):
Some custom javascript code and css styling are providing together with the application. This code will modify the instance styling and perform some specific adjustment in the data entry app.

In order to deploy this code we will need to install the custom js and css application from the dhis2 application store. It can be found at the following link and the installation process will be done using the regular Dhis2 application management.

Once installed, we have to access the custom js and css application in the Dhis2 instance. The application provides two options: javascript and style. We can copy the NRC customise code from the repository. Data-entry-contentscript.js content has to be copied into the javascript section while the nrc.css content has to be copied in the style section. We click on Save and from now on this customisation will be applied to the whole instance.

Tasks performed by our Js/Css code:
Fix the width of the “completeness box” (buttons Complete/Incomplete/Run Validation) 
Keep the CSS styles used by NRC.

---------------

If you have any doubt you can also double check on our dev instance (dev.eyeseetea) how the custom js/css app is installed and configured.
