### ISSUE TITLE
Dataset is not visible in the data entry form

### ISSUE THREAD

**Issue by ErikaMichelet** [EyeSeeTea/dataset-configuration-blessed#148]
I have a problem with an user in Kenya. He created datasets, but they are not visible in the data entry form.
I even created a new id for him, and it has changed nothing.
User name TKilunda
Password TKilunda1
Country Kenya
Dataset KEFM1801

**Comment by adrianq** [comment]
@ErikaMichelet This is a classic issue that we have solved a few times already. It doesn't have anything to do with the app but with the metadata

-------------------------

Find below the official explanation (sent to you in a previous mail):
If you go to the documentation page 22, you can read the following paragraph:
For each pair country-core competency a user role is extracted following the rule: [ContryCode] + ‘__dataset_’ + [CoreCompetency]. The new data set is added to each user role.  For this operation to succeed, the user must have **write sharing permission** (through a user group) on those user roles, otherwise a warning will be added to the notification message. Countries are extracted from the last step (Sharing). 

Let’s see an example:

Core Competencies: EDUCATION and SHELTER
Country: Jordan (JO) and Afghanistan (AF)
The saved dataset will be added to those user roles:
	JO__dataset_education
	JO__dataset_shelter
	AF__dataset_education
	AF__dataset_shelter

The purpose of this is for the app to add the data set to a user role whose sharing setting gives access to the user (through a user group).

------------

I have double checked and the dataset was not part of the user role. I have just added it manually and now KEFM1801 (UNHCR) Dataset is part of the user role (the app does this for you automatically if metadata is configured properly):
![screenshot from 2018-06-11 14-43-04](https://user-images.githubusercontent.com/6850223/41235132-f24f2340-6d85-11e8-9ee2-453edb234723.png)

I have duplicated TKilunda user and he can now see the dataset in data entry.

The real problem was however how the user roles were configured. This is how they were configured:
![screenshot from 2018-06-11 14-38-42](https://user-images.githubusercontent.com/6850223/41235247-4a05bf4a-6d86-11e8-8a20-b42a2acc239d.png)

and this is how they should be:
![screenshot from 2018-06-11 14-39-00](https://user-images.githubusercontent.com/6850223/41235250-4d830970-6d86-11e8-80a7-376948729064.png)

I haven't double checked all the user roles. If they are not properly configured you will have the same error when they try to create a new dataset for a different core competency.

Btw, you should have received an internal Dhis2 message when the dataset was created. It should also tell you if there was any warning or error message during the saving process. This is a very useful feature that we implemented in order to help you with this sort of problems....

Hope it is clear now...

**Comment by ErikaMichelet** [comment]
When creating datasets in the app, I am setting the sharing to both administrators and user. Thomas is part of KE_Administrators and KE_Users. Shouldn't it be enough?
 I changed the sharing settings to have KE_Administrators with edit rights and he cannot see most of them.

**Comment by adrianq** [comment]
If by the time they created the datasets the user roles were not properly configured the datasets have not been added to the user role. Therefore, even if you configure the user role properly now, you will have to go to the user role and add the dataset manually this time. The application tries to do it during the save process if it fails it will send you a warning message and create the dataset anyway.

@ErikaMichelet if you want to, drop me a line by mail and we can set up a hangout call and fix it together with screen sharing
