### ISSUE TITLE
Disaggregation consistency

### ISSUE THREAD

**Issue by ardhimanshu** [EyeSeeTea/dataset-configuration-blessed#168]
Indicators are based on data elements (numerator and denominator). We need to have some way of "forced" consistency of disaggregation for numerator and denominator data elements for any given indicator. For example, it should not allow any user to choose default in numerator and sex (male/female) in denominator.

**Comment by adrianq** [comment]
I see the problem. This is not difficult to implement. We already know this information as in step 4 and 5 the user selects the indicator that groups the data elements (numerator, denominator, comment). Not sure if we will be able to implement this as part of this week release. Otherwise, we will implement this for the following release.
