### ISSUE TITLE
Error on save

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-configuration-blessed#33]
TypeError: expecting an array or an iterable object but got [object Null]

**Comment by troyel** [comment]
Still got an error on save on 4.1 just now. It also does not appear to create sections.

**Comment by tokland** [comment]
Hi @troyel, what's the error? can you copy the message or send a screenshot? can you describe the steps (project/core competencies/dataelements/grey-fields...) so we can reproduce it?

**Comment by adrianq** [comment]
Can you provide more information about the dataset you are trying to create? sections, disaggregation if any, grey fields? Can you paste the error and the javascript error in the console?

**Comment by troyel** [comment]
![image](https://user-images.githubusercontent.com/22769102/29158678-334c52b6-7dac-11e7-8965-0979225cfaf5.png)
Same issue.
Steps to recreate:
New data set - ICLA and Education. Linked to a project.
Add two education local indicators CO-something.
Add one override somewhere.
Remove IDP male females dissagg all data elements.
Create -> Error.

**Comment by troyel** [comment]
(also assigned org unit Horn of Africa). Let me know if you have any issues recreate and I can be a little more specific or demonstrate over video

**Comment by tokland** [comment]
Hi @troyel, Adrian is on the road today, I'll take care of this. 

You are getting the same error "TypeError: expecting an array or an iterable object but got [object Null]" that we had, but that's really weird since we completely removed the external library that may raise this error. So I guess somehow you are running the old code. The first  try would be to clear completely the cache or, to be on the safe side, make a test on a chrome/firefox incognito tab. By the way, which user are you testing with, admin?

**Comment by troyel** [comment]
Clearing cache worked! Thanks!

**Comment by tokland** [comment]
Great! I guess Adrian already told you, but we detected a problem in the widget that displays grayed elements in the "Maintenance" app. It's noticeable when the same category is used on different catCombos within a section. In this case, the widget does not render the grayed fields table for that conflicting catCombos (and the JS console shows errors).
