### ISSUE TITLE
Edit lead to DS not loading

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#70]
I was going to change the "experiy date" field and changed only that then clicked next-next netxt and saved. The data entry form then doesn't load - often how it looks when there is a sharing issue - but I am admin, so that shouldn't really be an issue..

**Comment by troyel** [comment]
![DS not laoding.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590c634ad13d7b00206a7721/125516c66e82c728ace21e0d46cca7da2d8d97e983e8b047ad53f7d665043761260ea62864c7b96aea1a7854570e18ab48090e42fca8892ba4e53e74db580fecc3714d36976345f3e5db55ea43a82a994e82bcbd8f4dc0e0382de38f864938191755.PNG)

**Comment by adrianq** [comment]
Yep, you are right. This is definitely a bug. It should be pretty straight forward to fix it

**Comment by troyel** [comment]
Maybe we could (on edit) also have an early save button? If all I am saving is the change of name/dates then it could be saved immediately, right?

**Comment by adrianq** [comment]
Well, this is a bug we need to solve it. The bug has to do with clicking next 'too fast' so that some internal logic is not executed. We are working on it....

I have created another card to address that idea of an early save button (https://waffle.io/EyeSeeTea/dataset-configuration-blessed/cards/5a17e9af428518013e18860c). Will talk to @tokland and analyse how feasible it is to get it done for next release (around Wed next week)
