### ISSUE TITLE
When creating a ICLA data set it stop

### ISSUE THREAD

**Issue by troyel** [EyeSeeTea/dataset-configuration-blessed#97]
When trying to create a dataset with just all the standard selections on ICLA (seems to be outcome related?) for some reason I am not able to press "next" after selecting output&outcomes. Something in the metadata stops it - can't see any error message in the console?

**Comment by troyel** [comment]
update: does not seem to be (at least only) related to ICLA as creating a dataset with all indicators and removing all in ICLA still doesn't let me continue to the next step. Is it the amount of indicators or is there some metadata somewhere else blocking? Still no errors visible to me in console or network tab.. (Tips on where/how to troubleshoot this?)

**Comment by troyel** [comment]
It is great if you could look at this one soon. As it is the main thing I am waiting on at the momemt.

**Comment by tokland** [comment]
The code that shows a snack bar with the error message didn't make the 0.7.1 release, sorry, I'll make a patch so you can see it soon. This is what we should see when trying to create ICLA sections:

![screenshot from 2018-01-05 11-04-56](https://user-images.githubusercontent.com/24643/34604602-be90ccfa-f208-11e7-996d-ddecba10485c.png)

Does this error make sense? Note that sections with name like "ICLA Outcomes@@GL-LO3-1(m)," are being created because outcome sections are of the form _sectionName@theme@group_, where group is either the indicator group or, if empty, its code (as was requested on a previous task).

**Comment by troyel** [comment]
Thanks for the quick reply. Ok - that message is helpful.
